typography_spectrum: 0.4357956708408892
color:
  brandStrength: 0.5039497260004282
  lightness: 0.09982059663161635
  saturation: 0.6721851995680481
  rhythmicContrast: 0.4360215440392494
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.6976369861513376
name: Design Food Travel
title: Design
